{"name": "Проверка есть ли заказ в работе", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//ul[@class='OrderFeed_orderListReady__1YFem OrderFeed_orderList__cBvyi']/li[@class='text text_type_digits-default mb-2']; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <test_order_feed.TestOrderFeedPage object at 0x7e036f5e5990>, login_page = <pages.login_page.LoginPage object at 0x7e036f40c310>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"1a3c1f36-d398-4fb4-90ea-7989148af565\")>\norder_feed_page = <pages.order_feed_page.OrderFeedPage object at 0x7e036f40ccd0>\n\n    @allure.title('Проверка есть ли заказ в работе')\n    def test_order_in_work(self, login_page, driver, order_feed_page):\n        login_page.login()\n        home_page = HomePage(driver)\n        order_number = home_page.create_order_modification()\n        home_page.click_button_order_feed()\n>       order_number_in_work = order_feed_page.get_order_in_work()\n\ntests/test_order_feed.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/order_feed_page.py:33: in get_order_in_work\n    return self.get_element_text(OrderFeedPageLocators.NUMBER_ORDER_IN_WORK)\npages/base_page.py:55: in get_element_text\n    text = self.driver.find_element(*locator).text\n/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7e036f40d000>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"Unable to locate element: .//ul[@class=\\'Orde.../content/shared/webdriver/Errors.sys.mjs:511:5\\\\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//ul[@class='OrderFeed_orderListReady__1YFem OrderFeed_orderList__cBvyi']/li[@class='text text_type_digits-default mb-2']; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException"}, "steps": [{"name": "Логин", "status": "passed", "steps": [{"name": "Ввести логин в поле ввода", "status": "passed", "start": 1719663843810, "stop": 1719663843994}, {"name": "Ввести пароль в поле ввода", "status": "passed", "start": 1719663843994, "stop": 1719663844146}, {"name": "Нажать на кнопку Войти", "status": "passed", "start": 1719663844146, "stop": 1719663844406}], "start": 1719663843810, "stop": 1719663844406}, {"name": "Созать заказ с получение номера и закрытием модального окна", "status": "passed", "steps": [{"name": "Найти заголовок Соберите бургер", "status": "passed", "start": 1719663844406, "stop": 1719663844522}, {"name": "Перетащить ингредиент", "status": "passed", "steps": [{"name": "Перетаскивание элемента", "status": "passed", "parameters": [{"name": "source_element", "value": "<selenium.webdriver.remote.webelement.WebElement (session=\"1a3c1f36-d398-4fb4-90ea-7989148af565\", element=\"c40a39f9-692a-4f74-ba09-ad2544bde9fb\")>"}, {"name": "target_element", "value": "<selenium.webdriver.remote.webelement.WebElement (session=\"1a3c1f36-d398-4fb4-90ea-7989148af565\", element=\"243d0270-32e5-46ea-a798-a5e6e7760214\")>"}], "start": 1719663845130, "stop": 1719663845674}], "start": 1719663844522, "stop": 1719663845674}, {"name": "Нажать на кнопку Оформить заказ", "status": "passed", "start": 1719663845674, "stop": 1719663845962}, {"name": "Получить номер заказа", "status": "passed", "start": 1719663845962, "stop": 1719663847974}, {"name": "Закрыть модальное окно", "status": "passed", "steps": [{"name": "Ожидание скрытия элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//section//div/p[text()='Ваш заказ начали готовить']\")"}], "start": 1719663849342, "stop": 1719663849362}], "start": 1719663847974, "stop": 1719663849362}], "start": 1719663844406, "stop": 1719663849362}, {"name": "Нажать на кнопку Лента заказов", "status": "passed", "start": 1719663849362, "stop": 1719663851698}, {"name": "Получаем номер заказа в работе", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//ul[@class='OrderFeed_orderListReady__1YFem OrderFeed_orderList__cBvyi']/li[@class='text text_type_digits-default mb-2']; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/home/lisk/.local/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/lisk/Desktop/Diplom_3/pages/order_feed_page.py\", line 33, in get_order_in_work\n    return self.get_element_text(OrderFeedPageLocators.NUMBER_ORDER_IN_WORK)\n  File \"/home/lisk/.local/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/lisk/Desktop/Diplom_3/pages/base_page.py\", line 55, in get_element_text\n    text = self.driver.find_element(*locator).text\n  File \"/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Получить текст элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//ul[@class='OrderFeed_orderListReady__1YFem OrderFeed_orderList__cBvyi']/li[@class='text text_type_digits-default mb-2']; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/home/lisk/.local/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/lisk/Desktop/Diplom_3/pages/base_page.py\", line 55, in get_element_text\n    text = self.driver.find_element(*locator).text\n  File \"/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', \".//ul[@class='OrderFeed_orderListReady__1YFem OrderFeed_orderList__cBvyi']/li[@class='text text_type_digits-default mb-2']\")"}], "start": 1719663851698, "stop": 1719663851698}], "start": 1719663851698, "stop": 1719663851698}], "attachments": [{"name": "log", "source": "47b4874f-3bde-4402-8c07-40fd82f6fe03-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1719663843810, "stop": 1719663851698, "uuid": "c58f3af0-8a72-4074-807d-d67e188873d3", "historyId": "44c59a39f2d031eca46ba587278461af", "testCaseId": "d9fa0c659809e1b37ce741aa1ddd4477", "fullName": "tests.test_order_feed.TestOrderFeedPage#test_order_in_work", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed"}, {"name": "subSuite", "value": "TestOrderFeedPage"}, {"name": "host", "value": "lisk"}, {"name": "thread", "value": "48322-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed"}]}